<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async/Promise 2</title>
    <link rel="stylesheet" href="../css/execs-async.css">
    <link rel="stylesheet" href="../css/reset.css">
</head>

<body>
    <header>
        <div class="caixa">
            <h1><img src="../img/logo.png" class="logo"></h1>
            <nav>
                <ul>
                    <li><a href="../index.html">Home</a></li>
                    <li><a href="https://github.com/RafaFX">Github</a></li>
                </ul>
            </nav>
        </div>

    </header>

    <div class="box">

        <pre class="pre-code">
            <code>
                const promise1 = Promise.reject(0);
                const promise2 = new Promise(resolve => setTimeout(() =>
                resolve('first'), 100));
                const promise3 = new Promise(resolve => setTimeout(() =>
                resolve('second'), 500));
                const promises = [promise1, promise2, promise3];

                Promise.any(promises)
                .then((response) => {
                    console.log(response);
                }).catch((error) => {
                    console.log(`Ocorreu um erro: ${error}`);
                })
            </code>
        </pre>

    </div>

    <script>

        //2. Dada a seguinte lista de promises que são executadas ao mesmo tempo, crie
        //um código que retorna o resultado da primeira promise resolvida com
        //sucesso, independente se houve erro em alguma delas ou não.

        const promise1 = Promise.reject(0);
        const promise2 = new Promise(resolve => setTimeout(() =>
            resolve('first'), 100));
        const promise3 = new Promise(resolve => setTimeout(() =>
            resolve('second'), 500));
        const promises = [promise1, promise2, promise3];

        Promise.any(promises)
            .then((response) => {
                console.log(response);
            }).catch((error) => {
                console.log(`Ocorreu um erro: ${error}`);
            })

    </script>

    <footer>
        <p class="copyright">&copy; Copyright Rafael Lima - 2023</p>
    </footer>




</body>

</html>